executor:
  class_path: itwinai.backend.components.Executor
  init_args:
    steps:
      - class_path: dataloader.MNISTDataModuleTorch
        init_args:
          save_path: .tmp/

      - class_path: itwinai.backend.torch.trainer.TorchTrainerMG2
        init_args:
          model:
            class_path: model.Net
          loss:
            class_path: torch.nn.NLLLoss
            init_args:
              reduction: mean
          optimizer_class: torch.optim.SGD
          optimizer_kwargs: 
            lr: 0.001
          train_dataloader_kwargs:
            batch_size: 32
            pin_memory: True
            shuffle: True
          validation_dataloader_kwargs:
            batch_size: 32
            pin_memory: True
            shuffle: False
          epochs: 2
          strategy: ddp
          checkpoint_every: 1
          cluster:
            class_path: itwinai.cluster.LocalCluster
            init_args:
              gpus: null
              backend: nccl
