# Workflow definition in classical style
# Load with OmegaConf
# Other configuration files to merge with this file via OmegaConf
conf-dependencies:
  - meta.yml

steps:
  - Training:
      doc: Run Tensorflow Cyclone training
      command: python ${root}/trainval.py
      env:
        file: ${root}/env-files/tensorflow-env.yml
        prefix: ${root}/.venv-tensorflow
      args:
        batch_size: 16
        epochs: 1
        main_dir: ${root}
