apiVersion: apps/v1
kind: Deployment
metadata:
  name: itwinai-deployment
  labels:
    app: itwinai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itwinai
  template:
    metadata:
      labels:
        app: itwinai
    spec:
      containers:
      - name: itwinai
        image: ghcr.io/intertwin-eu/t6.5-ai-and-ml:containers
        #imagePullPolicy: Never
	resources:
	  requests:
            memory: "100Mi"
      	  limits:
            memory: "200Mi"
        ports:
        - containerPort: 80


