# Configuration file of AI workflows for MNIST use case

experiment_name: MNIST classification lite
description: A MLP classifier for MNIST dataset.
model: itwinai.plmodels.mnist.LitMNIST
max_epochs: 2
log_every_n_steps: 1
accelerator: auto
devices: auto

# Have to coincide with constructor param names
hyperparams:
  learning_rate: 0.001
  batch_size: 32
  hidden_size: 64
