datasets:
  preproc-images-train:
    location: ./data/mnist/preproc-images-train
  ml-logs:
    location: ./data/mnist/ml-logs

steps:
  - preprocessing:
      input: null
      output: preproc-images-train
      command: python ./use-cases/mnist/mnist-preproc.py
      env: 
        file: ./use-cases/mnist/preproc-env.yml
        prefix: ./use-cases/mnist/.venv-preproc
        source: null
      params: null
  - ml-training:
      input: preproc-images-train
      output: ml-logs
      # command: python ./ai/ai-training.py
      command: itwinai train
      env: 
        file: ./ai/training-env.yml
        prefix: ./ai/.venv-training
        source: ./ai
      params:
        config: ./use-cases/mnist/mnist-ai.yml