#Workflow definition in classical style
datasets:
  preproc-images:
    location: ./data/mnist/preproc-images
  ml-logs:
    # MLflow tracking URI
    location: ./data/mnist/ml-logs

steps:
  - preprocessing:
      input: null
      output: preproc-images
      command: python ./use-cases/mnist/mnist-preproc.py
      env: 
        file: ./use-cases/mnist/preproc-env.yml
        prefix: ./use-cases/mnist/.venv-preproc
        source: null
      params: null
  - ml-training:
      input: preproc-images
      output: ml-logs
      command: itwinai train
      env: 
        file: ./ai/pytorch-env.yml
        prefix: ./ai/.venv-pytorch
        source: ./ai
      params:
        config: ./use-cases/mnist/mnist-ai.yml

# #Workflow definition in CWL style

# workflowFileCWL: use-cases/mnist/workflow.cwl

# preprocessEnvironment:
#   class: Directory
#   path: .venv-preproc

# preprocessScript:
#   class: File
#   path: mnist-preproc.py

# #Placeholder for input dataset
# # preprocessInput:
# #   class: Directory
# #   path:

# preprocessOutput:
#   class: Directory
#   path: ../../data/mnist/preproc-images

# #training step
# trainingConfig:
#   class: File
#   path: mnist-ai.yml

# trainingEnvironment:
#   class: Directory
#   path: ../../ai/.venv-training

# trainingCommand: train