#Workflow definition in classical style
datasets:
  preproc-images-train:
    location: ./data/mnist/preproc-images-train
  ml-logs:
    location: ./data/mnist/ml-logs

steps:
  - preprocessing:
      input: null
      output: preproc-images-train
      command: python ./use-cases/mnist/mnist-preproc.py
      env: 
        file: ./use-cases/mnist/preproc-env.yml
        prefix: ./use-cases/mnist/.venv-preproc
        source: null
      params: null
  - ml-training:
      input: preproc-images-train
      output: ml-logs
      # command: python ./ai/ai-training.py
      command: itwinai train
      env: 
        file: ./ai/training-env.yml
        prefix: ./ai/.venv-training
        source: ./ai
      params:
        config: ./use-cases/mnist/mnist-ai.yml

#Workflow definition in CWL style

workflowFileCWL: use-cases/mnist/workflow.cwl

preprocessEnvironment:
  class: Directory
  path: .venv-preproc

preprocessScript:
  class: File
  path: mnist-preproc.py

#Placeholder for input dataset
# preprocessInput:
#   class: Directory
#   path:

preprocessOutput:
  class: Directory
  path: ../../data/mnist/preproc-images-train

#training step
trainingConfig:
  class: File
  path: mnist-ai.yml

trainingEnvironment:
  class: Directory
  path: ../../ai/.venv-training

trainingCommand: train