###Preprocessing ###

preprocessEnvironment:
  class: Directory
  path: .venv-preproc

preprocessScript:
  class: File
  path: mnist-preproc.py

#Placeholder for input dataset
# preprocessInput:
#   class: Directory
#   path:

preprocessOutput:
  class: Directory
  path: ../../data/mnist/preproc-images-train

### Training ###
trainingConfig:
  class: File
  path: mnist-ai.yml

trainingEnvironment:
  class: Directory
  path: ../../ai/.venv-training

trainingCommand: train

#setup
steps:
  - preprocessing:
      env: 
        file: ./use-cases/mnist/preproc-env.yml
        prefix: ./use-cases/mnist/.venv-preproc
        source: null
  - ml-training:
      env: 
        file: ./ai/training-env.yml
        prefix: ./ai/.venv-training
        source: ./ai


