executor:
  class_path: itwinai.backend.components.Executor
  init_args:
    steps:
      - class_path: dataloader.MNISTDataModuleTorch
        init_args:
          save_path: .tmp/
          batch_size: 32
          pin_memory: True
          num_workers: 4

      - class_path: itwinai.backend.torch.trainer.TorchTrainer
        init_args:
          model:
            class_path: model.Net
          loss:
            class_path: torch.nn.NLLLoss
            init_args:
              reduction: mean
          optimizer_class: torch.optim.SGD
          optimizer_kwargs: 
            lr: 0.001
          epochs: 2
          strategy: ddp
          backend: nccl
          checkpoint_every: 1