channels:
- conda-forge
dependencies:
- python=3.9.12
- pip<=23.1.2
- pip:
  - mlflow==2.3
  - attrs==23.1.0
  - cffi==1.15.1
  - click==8.1.3
  - cloudpickle==2.2.1
  - configparser==5.3.0
  - docstring-parser==0.15
  - html5lib==1.1
  - itwinai==0.1
  - lightning==2.0.0
  - numpy==1.24.3
  - omegaconf==2.3.0
  - orjson==3.8.14
  - packaging==23.1
  - pyyaml==6.0
  - requests==2.31.0
  - torch==1.13.1
  - torchvision==0.14.1
  - typeshed-client==2.3.0
name: mlflow-env
