# Configuration file of AI workflows for MNIST use case
# Load with OmegaConf

# Other configuration files to merge with this file via OmegaConf 
conf-dependencies:
  - meta.yml

# Inference configuration
inference:
  type: lightning
  experiment_name: MNIST classification lite
  # Run ID in MLFlow server: pre-trained model
  run_id: f9135e1b391f429d88818201fdf43e24
  ckpt_path: model/checkpoints/best-checkpoint/best-checkpoint.ckpt
  train_config_artifact_path: pl-training.yml
  conf:
    # Lightning data module configuration
    data:
      class_path: itwinai.plmodels.mnist.MNISTDataModule
      init_args:
        data_dir: ${cli.input_dataset}
        batch_size: 32