apiVersion: v1
kind: Pod
metadata:
  name: training
spec:
  containers:
    - name: mlflow-container
      image: ghcr.io/intertwin-eu/t6.5-ai-and-ml:containers
      command: ["mlflow"]
      args: ["server", "--backend-store-uri", "/home/T6.5-AI-and-ML/use-cases/mnist/data/ml-logs/"]
      
    - name: itwinai-container
      image: ghcr.io/intertwin-eu/t6.5-ai-and-ml:containers
      command: ["itwinai"]
      args: ["train", "--train-dataset", "/home/T6.5-AI-and-ML/use-cases/mnist/data/preproc-images", "--config", "/home/T6.5-AI-and-ML/use-cases/mnist/mnist-ai-train.yml", "--ml-logs", "http://127.0.0.1:5000"]
