apiVersion: apps/v1
kind: Deployment
metadata:
  name: training
  labels:
    app: training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training
  template:
    metadata:
      labels:
        app: training
    spec:
      containers:
        - name: mlflow-container
          image: ghcr.io/intertwin-eu/t6.5-ai-and-ml:containers
          command: ["mlflow"]
          args: ["server", "--backend-store-uri", "/home/T6.5-AI-and-ML/use-cases/mnist/data/ml-logs/"]
          volumeMounts:
          - name: eos
            mountPath: /eos
            mountPropagation: HostToContainer
          
        - name: itwinai-container
          image: ghcr.io/intertwin-eu/t6.5-ai-and-ml:containers
          command: ["itwinai"]
          args: ["train", "--train-dataset", "/home/T6.5-AI-and-ML/use-cases/mnist/data/preproc-images", "--config", "/eos/home-a/azoechba/mnist-ai-train.yml", "--ml-logs", "http://127.0.0.1:5000"]
          volumeMounts:
          - name: eos
            mountPath: /eos
            mountPropagation: HostToContainer


      volumes:
        - name: eos
          # Note the particularity of the host path being /var/eos, not /eos.
          # The path inside the container will be /eos with this sample setup.
          hostPath:
            path: /var/eos
      securityContext:
        seLinuxOptions:
          type: "spc_t"