name: ai-training
channels:
  - conda-forge
  - pytorch
  # - nvidia
dependencies:
  - python=3.9.12
  - pytorch::pytorch=1.13.1
  - pytorch::torchvision
  - pytorch::cpuonly
  - lightning
  - torchmetrics
  - mlflow>=2
  - typer
  - rich
  - pyyaml