model:
  class_path: itwinai.plmodels.mnist.LitMNIST
  init_args: 
    data_dir: ../data/mnist/preproc-images-train
    learning_rate: 0.001
    batch_size: 32
    hidden_size: 64

car: my car
number: 3
