---
name: Test workflows

on:
  push:
  pull_request:

jobs:
  test:
    name: Test DT workflows
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: Install micromamba
        shell: bash -l {0}
        run: |
          curl micro.mamba.pm/install.sh | bash
          micromamba --version
      
      - name: Make workflow runner
        shell: bash -l {0}
        run: make workflow-runner-cern

      - name: Run pytest for workflows
        shell: bash -l {0}
        run: conda run -p ./.venv pytest ./tests/
