---
name: Test workflows

on:
  push:
  pull_request:

jobs:
  test:
    name: Test DT workflows
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: Install micromamba
        shell: bash -l {0}
        run: curl micro.mamba.pm/install.sh | bash

      - name: check
        run: micromamba --version

      - name: check2
        run: mamba --version

