---
name: Test workflows

on:
  push:
  pull_request:

jobs:
  test:
    name: Test DT workflows
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: Install micromamba
        shell: bash -l {0}
        run: curl micro.mamba.pm/install.sh | bash

      - name: check
        # shell: bash -l {0}
        run: |
          micromamba --version
      
      - name: make
        shell: bash -l {0}
        run: make



      # - name: check2
      #   run: echo 'alias mamba="micromamba"' >> ~/.bashrc
      #   shell: bash -l {0}
      # - run: mamba --version
      #   shell: bash -l {0}
      # - run: make
      #   shell: bash -l {0}

