---
name: Test Python

on:
  push:
  pull_request:

jobs:
  test:
    name: Test itwinai with pytest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Conda environment with Micromamba for dev env (pytest)
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: dev-env.yml
          micromamba-version: "1.4.3"
          environment-name: dev-env
          cache-downloads: true
          cache-env: true
          # channels: pytorch,nvidia,conda-forge
        
        shell: bash -l {0}
        run: pytest ai/tests
