---
name: Test Python

on:
  push:
  pull_request:

jobs:
  test:
    name: Test Python wth pytest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - name: Install Conda environment with Micromamba for workflow runner
      #   uses: mamba-org/provision-with-micromamba@main
      #   with:
      #     environment-file: environment-cern.yml
      #     environment-name: workflow-runner
      #     cache-downloads: true

      - name: Install Conda environment with Micromamba for dev env (pytest)
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: dev-env1.yml
          environment-name: dev-env
          # cache-downloads: true
          # channels: pytorch, conda-forge
        
      # - name: Run tests
      #   shell: bash -l {0}
      #   run: conda run -n dev-env pytest
