# SPDX-FileCopyrightText: Copyright contributors to the Software Quality Assurance as a Service (SQAaaS) project.
#
# SPDX-License-Identifier: GPL-3.0-only
---
name: SQAaaS

on:
  push:
    branches: [main, dev, unit_test_4_dev]
  pull_request:
    branches: [main, dev, unit_test_4_dev]

jobs:
  sqaaas_job:
    runs-on: ubuntu-latest
    name: Job that triggers SQAaaS platform
    steps:
      - name: Step definition for a SQAaaS assessment
        uses: eosc-synergy/sqaaas-step-action@v1
        with:
          name: workflow_validation_step
          tool: commands
          commands: |
            make torch-cpu
            make tf-2.13
            micromamba run -p ./.venv-pytorch pip install .[dev]
            micromamba run -p ./.venv-pytorch pytest -v ./tests/ -m "not slurm"
          container: eoscsynergy/sqaaas-micromamba:1.5.3-1
      - name: Print out payload
        run: cat workflow_validation_step.json
      - name: SQAaaS assessment step
        uses: eosc-synergy/sqaaas-assessment-action@v2
        with:
          steps: workflow_validation_step
