---
name: Test workflows

on:
  # push:
  pull_request:

jobs:
  test-itwinai:
    name: Test itwinai with pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Install micromamba
        shell: bash -l {0}
        run: |
          "${SHELL}" <(curl -L micro.mamba.pm/install.sh)
      
      - name: Make torch CPU env
        shell: bash -l {0}
        run: make torch-cpu

      - name: Install dev version
        shell: bash -l {0}
        run: micromamba run -p ./.venv-pytorch pip install .[dev]

      - name: Run pytest for workflows
        shell: bash -l {0}
        run: micromamba run -p ./.venv-pytorch pytest -v ./tests/ -m "not distributed"



  test-itwinai:
    name: Test itwinai with pytest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install micromamba environment with Micromamba for dev env (pytest)
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: dev-env.yml
          micromamba-version: "1.4.3"
          environment-name: dev-env
          cache-downloads: true
          cache-env: true
          # channels: pytorch,nvidia,conda-forge
      - name: Install itwinai
        shell: bash -l {0}
        run: python -m pip install --no-deps -e ./ai
      - name: Run tests
        shell: bash -l {0}
        run: pytest ai/tests

